name: sonar-net
description: Create SonarQube report
inputs:
  path:
    required: true
    description: Project path
  project_name:
    required: true
    description: project name
  sonar_server:
    required: true
    description: Sonar server url
  sonar_token:
    required: true
    description: sonar token
  nexus_user:
    required: false
    description: nexus user
  nexus_pass:
    required: false
    description: nexus pass

runs:
  using: "composite"
  steps:      
      - name: Copy and configure nuget.config
        working-directory: ${{ inputs.path }}
        run: |
          if [ -f nuget.config.template ]; then
            cp nuget.config.template nuget.config
            sed -i -e "s/USER/${{ inputs.nexus_user }}/g" -e "s/PW/${{ inputs.nexus_pass }}/g" nuget.config
          else
            echo "nuget.config.template does not exist. Skipping."
          fi
        shell: bash

      - name: Install SonarScanner for .NET
        run: |
          if ! dotnet tool list -g | grep -q dotnet-sonarscanner; then
            dotnet tool install --global dotnet-sonarscanner
          else
            echo "dotnet-sonarscanner already installed"
          fi
        shell: bash
      
      - name: Run SonarScanner
        env:
          DOTNET_CLI_HOME: /root
        run: |          
          dotnet sonarscanner begin /k:'20_Omicron_AppiOSFormulas_${{ inputs.project_name }}' /d:sonar.host.url='${{ inputs.sonar_server }}' /d:sonar.token='${{ inputs.sonar_token }}' /d:sonar.cs.opencover.reportsPaths='Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test/TestResults/coverage.opencover.xml' /d:sonar.coverage.exclusions='**Test*.cs, **/Controllers/**/*, **DependencyInjector.cs, **Startup.cs, **Program.cs, Omicron.${{ inputs.project_name }}.Api/**' &&
          dotnet build Omicron.${{ inputs.project_name }}.Microservice.sln &&
          dotnet test Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"TestResults/\" &&
          dotnet sonarscanner end /d:sonar.login='${{ inputs.sonar_token }}'
        working-directory: ${{ inputs.path }}
        shell: bash