//<auto-generated/>

global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using Newtonsoft.Json;
global using NUnit.Framework;
global using Omicron.Usuarios.DataAccess.DAO.User;
global using Omicron.Usuarios.Dtos.Models;
global using Omicron.Usuarios.Dtos.User;
global using Omicron.Usuarios.Entities.Context;
global using Omicron.Usuarios.Entities.Model;
global using Omicron.Usuarios.Facade.Catalogs.Users;
global using Omicron.Usuarios.Resources.Exceptions;
global using Omicron.Usuarios.Services.Constants;
global using Omicron.Usuarios.Services.Mapping;
global using Omicron.Usuarios.Services.Pedidos;
global using Omicron.Usuarios.Services.SapAdapter;
global using Omicron.Usuarios.Services.User;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using Omicron.Usuarios.Services.Catalogos;

