// <auto-generated/>


global using AutoFixture;
global using AutoMapper;
global using Azure.Storage.Blobs.Models;
global using Microsoft.Extensions.Configuration;
global using Moq;
global using Moq.Protected;
global using Newtonsoft.Json;
global using NUnit.Framework;
global using Omicron.Reporting.Dtos.Model;
global using Omicron.Reporting.Entities.Model;
global using Omicron.Reporting.Facade.Request;
global using Omicron.Reporting.Resources.Exceptions;
global using Omicron.Reporting.Resources.Extensions;
global using Omicron.Reporting.Services;
global using Omicron.Reporting.Services.AzureServices;
global using Omicron.Reporting.Services.Clients;
global using Omicron.Reporting.Services.Mapping;
global using Omicron.Reporting.Services.ServiceLayerAdapter;
global using Serilog;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Net.Mail;
global using System.Threading;
global using System.Threading.Tasks;

