# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Omicron' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Omicron
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'ObjectMapper'
  pod 'lottie-ios'
  pod 'Eureka'
  pod 'Resolver'
  pod 'SignaturePad', '~> 1.0.3'
  pod 'TagListView', '~> 1.0'
  pod 'RxDataSources'
  pod 'Charts'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  
  target 'OmicronQA' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for OmicronQA
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Moya/RxSwift', '~> 14.0'
    pod 'ObjectMapper'
    pod 'lottie-ios'
    pod 'Eureka'
    pod 'Resolver'
    pod 'SignaturePad', '~> 1.0.3'
    pod 'TagListView', '~> 1.0'
    pod 'RxDataSources'
    pod 'Charts'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    end
    
    target 'OmicronDEV' do
      # Comment the next line if you don't want to use dynamic frameworks
      use_frameworks!

      # Pods for OmicronDEV
      pod 'RxSwift'
      pod 'RxCocoa'
      pod 'Moya/RxSwift', '~> 14.0'
      pod 'ObjectMapper'
      pod 'lottie-ios'
      pod 'Eureka'
      pod 'Resolver'
      pod 'SignaturePad', '~> 1.0.3'
      pod 'TagListView', '~> 1.0'
      pod 'RxDataSources'
      pod 'Charts'
      pod 'Firebase/Analytics'
      pod 'Firebase/Crashlytics'
      end
 
  target 'OmicronTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OmicronUITests' do
    # Pods for testing
  end

end
