# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '15.6'

target 'Omicron' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Omicron
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'lottie-ios'
  pod 'Eureka'
  pod 'Resolver'
  pod 'SignaturePad', '~> 1.0.3'
  pod 'TagListView'
  pod 'RxDataSources'
  pod 'DGCharts'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'HorizonCalendar'
  
  target 'OmicronQA' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Pods for OmicronQA
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Moya/RxSwift'
    pod 'ObjectMapper'
    pod 'lottie-ios'
    pod 'Eureka'
    pod 'Resolver'
    pod 'SignaturePad', '~> 1.0.3'
    pod 'TagListView'
    pod 'RxDataSources'
    pod 'DGCharts'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'HorizonCalendar'
    end
    
    target 'OmicronDEV' do
      # Comment the next line if you don't want to use dynamic frameworks
      use_frameworks!

      # Pods for OmicronDEV
      pod 'RxSwift'
      pod 'RxCocoa'
      pod 'Moya/RxSwift'
      pod 'ObjectMapper'
      pod 'lottie-ios'
      pod 'Eureka'
      pod 'Resolver'
      pod 'SignaturePad', '~> 1.0.3'
      pod 'TagListView'
      pod 'RxDataSources'
      pod 'DGCharts'
      pod 'Firebase/Analytics'
      pod 'Firebase/Crashlytics'
      pod 'HorizonCalendar'
      end
    
    target 'OmicronUAT' do
      # Comment the next line if you don't want to use dynamic frameworks
      use_frameworks!

      # Pods for OmicronDEV
      pod 'RxSwift'
      pod 'RxCocoa'
      pod 'Moya/RxSwift'
      pod 'ObjectMapper'
      pod 'lottie-ios'
      pod 'Eureka'
      pod 'Resolver'
      pod 'SignaturePad', '~> 1.0.3'
      pod 'TagListView'
      pod 'RxDataSources'
      pod 'DGCharts'
      pod 'Firebase/Analytics'
      pod 'Firebase/Crashlytics'
      pod 'HorizonCalendar'
      end
 
  target 'OmicronTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OmicronUITests' do
    # Pods for testing
  end
end
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end
