// <auto-generated/>
global using System.Net.Http;
global using System.Text;
global using System.Threading.Tasks;
global using AutoMapper;
global using Axity.Commons.Exceptions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Newtonsoft.Json;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Orders;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Responses;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Responses.Common;
global using Omicron.SapServiceLayerAdapter.Model;
global using Omicron.SapServiceLayerAdapter.Services.Constants;
global using Omicron.SapServiceLayerAdapter.Services.Mapping;
global using Omicron.SapServiceLayerAdapter.Services.Orders;
global using Omicron.SapServiceLayerAdapter.Services.Orders.Impl;
global using Omicron.SapServiceLayerAdapter.Services.ServiceLayer;
global using Omicron.SapServiceLayerAdapter.Services.ServiceLayer.Impl;
global using Omicron.SapServiceLayerAdapter.Services.Utils;
global using Serilog;

