apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: omicron-web-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  externalIPs:
    - 192.168.0.101
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimanager-deployment
  labels:
    app: apimanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apimanager
  template:
    metadata:
      labels:
        app: apimanager
    spec:
      containers:
        - name: apimanager
          image: omicron-apimanager-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: apimanager-svc
  labels:
    app: apimanager-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: apimanager
  externalIPs:
    - 192.168.0.101
  selector:
    app: apimanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver-deployment
  labels:
    app: oauthserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
        - name: oauthserver
          image: omicron-oauthserver-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogos-deployment
  labels:
    app: catalogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogos
  template:
    metadata:
      labels:
        app: catalogos
    spec:
      containers:
        - name: catalogos
          image: omicron-catalogos-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 9010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  labels:
    app: usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: omicron-usuarios-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapadapter-deployment
  labels:
    app: sapadapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapadapter
  template:
    metadata:
      labels:
        app: sapadapter
    spec:
      containers:
        - name: sapadapter
          image: omicron-sapadapter-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5102
          livenessProbe:
            httpGet:
              path: /hc
              port: 5102
            initialDelaySeconds: 30
            periodSeconds: 300
            timeoutSeconds: 40
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
  labels:
    app: pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: omicron-pedidos-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses-deployment
  labels:
    app: warehouses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouses
  template:
    metadata:
      labels:
        app: warehouses
    spec:
      containers:
        - name: warehouses
          image: omicron-warehouses-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: omicron-reporting-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 5105
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seqlog-deployment
  labels:
    app: seqlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seqlog
  template:
    metadata:
      labels:
        app: seqlog
    spec:
      containers:
        - name: seqlog
          image: datalust/seq:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 80
              name: intra
            - containerPort: 5341
              name: extra
---
apiVersion: v1
kind: Service
metadata:
  name: seqlog-svc
  labels:
    app: seqlog
spec:
  type: LoadBalancer
  ports:
    - name: default
      port: 81
      targetPort: 80
      protocol: TCP
    - name: alt
      port: 5341
      targetPort: 5341
      protocol: TCP
  externalIPs:
    - 192.168.0.101
  selector:
    app: seqlog
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: notify-keyspace-events KEx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdata-deployment
  labels:
    app: redisdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdata
  template:
    metadata:
      labels:
        app: redisdata
    spec:
      containers:
        - name: redisdata
          image: redis:alpine
          args:
            - /etc/redis/redis.conf
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redisdata-svc
  labels:
    app: redisdata
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  externalIPs:
    - 192.168.0.101
  selector:
    app: redisdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaconsumer-deployment
  labels:
    app: kafkaconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaconsumer
  template:
    metadata:
      labels:
        app: kafkaconsumer
    spec:
      containers:
        - name: kafkaconsumer
          image: omicron-kafkaconsumer-repository
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
