apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimanager-deployment
  labels:
    app: apimanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apimanager
  template:
    metadata:
      labels:
        app: apimanager
    spec:
      containers:
        - name: apimanager
          image: omicron.azurecr.io/omicron-apimanager-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver-deployment
  labels:
    app: oauthserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
        - name: oauthserver
          image: omicron.azurecr.io/omicron-oauthserver-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: POSTGRESS_JDBC_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_jdbc_postgress_db
          ports:
            - containerPort: 8090
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogos-deployment
  labels:
    app: catalogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogos
  template:
    metadata:
      labels:
        app: catalogos
    spec:
      containers:
        - name: catalogos
          image: omicron.azurecr.io/omicron-catalogos-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
          ports:
            - containerPort: 9010
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  labels:
    app: usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: omicron.azurecr.io/omicron-usuarios-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
          ports:
            - containerPort: 5101
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapadapter-deployment
  labels:
    app: sapadapter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sapadapter
  template:
    metadata:
      labels:
        app: sapadapter
    spec:
      containers:
        - name: sapadapter
          image: omicron.azurecr.io/omicron-sapadapter-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: redis
            - name: SAP_CONNECTION_STRING_SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: sap_connection_string_sql_server
            - name: OMICRON_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_file_url
          ports:
            - containerPort: 5102
    imagePullSecrets:
      - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
  labels:
    app: pedidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: omicron.azurecr.io/omicron-pedidos-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: redis
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
            - name: EVENHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: eventhub_net_connection
            - name: SAP_DI_API_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: sap_di_api_url
            - name: SAP_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: sap_file_url
            - name: OMICRON_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_file_url
            - name: STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: storage_account
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: storage_account_key
          ports:
            - containerPort: 5103
    imagePullSecrets:
      - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses-deployment
  labels:
    app: warehouses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouses
  template:
    metadata:
      labels:
        app: warehouses
    spec:
      containers:
        - name: warehouses
          image: omicron.azurecr.io/omicron-warehouses-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
          ports:
            - containerPort: 5104
    imagePullSecrets:
      - name: pullsecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: omicron.azurecr.io/omicron-reporting-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
          ports:
            - containerPort: 5105
    imagePullSecrets:
      - name: pullsecret
