apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: Omicron-web-repository
        env:
        - name: TZ
          value: America/Mexico_City
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  externalIPs:
    - 192.168.0.101
  selector:
    app: web 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimanager-deployment
  labels:
    app: apimanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apimanager
  template:
    metadata:
      labels:
        app: apimanager
    spec:
      containers:
      - name: apimanager
        image: Omicron-apimanager-repository
        env:
        - name: TZ
          value: America/Mexico_City
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: apimanager-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  externalIPs:
    - 192.168.0.101
  selector:
    app: apimanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver-deployment
  labels:
    app: oauthserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
      - name: oauthserver
        image: Omicron-oauthserver-repository
        env:
        - name: TZ
          value: America/Mexico_City
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: oauthserver-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
  externalIPs:
    - 192.168.0.101
  selector:
    app: oauthserver 