apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4180
          args:
            - --provider=keycloak-oidc
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-secure=false
            - --whitelist-domain=devtools.axity.com
            - --cookie-domain=devtools.axity.com
            - --redirect-url=https://devtools.axity.com/oauth2/callback
            - --skip-provider-button=false
            - --set-xauthrequest=true
            - --skip-auth-preflight=false
            - --reverse-proxy=true
            - --skip-jwt-bearer-tokens=true
            - --set-authorization-header=true
            - --oidc-issuer-url=https://devtools.axity.com/auth/realms/omicron
            - --email-domain=*
            - --standard-logging
            - --auth-logging
            - --request-logging
            - --auth-logging-format={{.Client}} - {{.RequestID}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}] {{.Message}}
            - --request-logging-format={{.Client}} - {{.RequestID}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}
            - --standard-logging-format=[{{.Timestamp}}] [{{.File}}] {{.Message}}
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: oauth2-proxy
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: eac0dd1a-19ef-4e5e-b0c0-2e3bf2bba15e
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: pJdWThtHznkeZsYyC4TRxg==
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4180
  selector:
    app: oauth2-proxy
  type: ClusterIP
