name: 'Docker build and push to ECR'
description: 'Deploy a web Angular to ECR'
inputs:
  working_directory:
    description: 'Working directory'
    required: true
  registry:
    description: 'Elastic Container Registry Name'
    required: true
  repository:
    description: 'Repository Name (Exist)'
    required: true
  tag:
    description: 'Tag Docker Image'
    required: true
  nexus_user:
    description: 'Nexus user'
    required: false
  nexus_pass:
    description: 'Nexus password'
    required: false
  dockerfile:
    description: 'Dockerfile name'
    required: false
    default: Dockerfile
  aws_nuget_auth_token:
    description: 'Nuget Token Authorization'
    required: false
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AXITY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AXITY_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get AWS Nuget Token Action
      run: |
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain axity --domain-owner 992382646884 --region us-east-1 --query authorizationToken --output text)
        echo "NUGET_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV
      shell: bash

    - name: Build and push docker image to Amazon ECR
      working-directory: ${{ inputs.working_directory }}
      run: |
        docker build -f ${{ inputs.dockerfile }} --build-arg NUGET_AUTH_TOKEN=${{ inputs.aws_nuget_auth_token }} --build-arg NUGET_USER_NAME=${{ inputs.nexus_user }} -t ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }} -t ${{ inputs.registry }}/${{ inputs.repository }}:latest . --progress=plain
        docker push ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }}
        docker push ${{ inputs.registry }}/${{ inputs.repository }}:latest
        docker image prune -af
      shell: bash