// <auto-generated/>


global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using NUnit.Framework;
global using Omicron.Catalogos.DataAccess.DAO.Catalog;
global using Omicron.Catalogos.DataAccess.DAO.User;
global using Omicron.Catalogos.Dtos.User;
global using Omicron.Catalogos.Entities.Context;
global using Omicron.Catalogos.Entities.Model;
global using Omicron.Catalogos.Facade.Catalogs;
global using Omicron.Catalogos.Facade.Catalogs.Users;
global using Omicron.Catalogos.Services.Catalogs;
global using Omicron.Catalogos.Services.Mapping;
global using Omicron.Catalogos.Services.User;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
