// <auto-generated/>


global using AutoFixture;
global using AutoMapper;
global using ClosedXML.Excel;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using NUnit.Framework;
global using Microsoft.Extensions.Configuration;
global using Omicron.Catalogos.Services.Redis;
global using Omicron.Catalogos.DataAccess.DAO.Catalog;
global using Omicron.Catalogos.DataAccess.DAO.User;
global using Omicron.Catalogos.Services.CatalogsDxp;
global using Omicron.Catalogos.Dtos.User;
global using Omicron.Catalogos.Dtos.Models;
global using Omicron.Catalogos.Dtos.SapAdapter;
global using Omicron.Catalogos.Entities.Context;
global using Omicron.Catalogos.Entities.Model;
global using Omicron.Catalogos.Facade.Catalogs;
global using Omicron.Catalogos.Facade.Catalogs.Users;
global using Omicron.Catalogos.Services.Catalogs;
global using Omicron.Catalogos.Services.Constants;
global using Omicron.Catalogos.Services.Mapping;
global using Omicron.Catalogos.Services.User;
global using Omicron.Catalogos.Services.SapAdapter;
global using Newtonsoft.Json;
global using Serilog;
global using System;
global using System.Data;
global using System.IO;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using StackExchange.Redis;
