// <auto-generated/>
global using Omicron.Invoice.Facade.Users;
global using Omicron.Invoice.Facade.Users.Impl;
global using Omicron.Invoice.Services.Invoice;
global using Microsoft.Extensions.DependencyInjection;
global using Omicron.Invoice.Common.DTOs.Requests.Invoices;
global using Omicron.Invoice.Common.DTOs.Responses.Common;
global using System.Net;
global using Omicron.Invoice.Services.Utils;