// <auto-generated/>
global using Microsoft.Extensions.DependencyInjection;
global using Omicron.Invoice.Common.DTOs.Requests.InvoiceRetry;
global using Omicron.Invoice.Common.DTOs.Responses.Common;
global using Omicron.Invoice.Common.DTOs.Responses.Users;
global using Omicron.Invoice.Facade.InvoiceRetry;
global using Omicron.Invoice.Facade.InvoiceRetry.Impl;
global using Omicron.Invoice.Facade.Users;
global using Omicron.Invoice.Facade.Users.Impl;
global using Omicron.Invoice.Services.Invoice;
global using Omicron.Invoice.Services.InvoiceRetry;