// <auto-generated/>
global using Omicron.Invoice.Common.DTOs.Requests.Users;
global using Omicron.Invoice.Common.DTOs.Responses.Users;
global using Omicron.Invoice.Facade.Users;
global using Omicron.Invoice.Facade.Users.Impl;
global using Omicron.Invoice.Services.Users;
global using Microsoft.Extensions.DependencyInjection;