// <auto-generated/>
using Microsoft.AspNetCore.Builder;

const string APP_NAME = "ARQUETIPO NET 6";
try
{
    Log.Information($"{APP_NAME} service starting.");
    var builder = WebApplication.CreateBuilder(args);
    builder.Host.AddPlaceholderResolver();
    Log.Logger = new LoggerConfiguration()
                    .MinimumLevel.Information()
                    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                    .MinimumLevel.Override("System", LogEventLevel.Warning)
                    .CreateLogger();
    builder.Host.UseSerilog(Log.Logger);
    builder
        .AppConfiguration()
        .UseApplication()
        .Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, $"{APP_NAME} service failed to start.");
}
finally
{
    Log.CloseAndFlush();
}