// <auto-generated/>

const string APP_NAME = "Invoice Microservice";
try
{
    Log.Information($"{APP_NAME} service starting.");
    var builder = WebApplication.CreateBuilder(args);
    builder.Host.AddPlaceholderResolver();
    Log.Logger = new LoggerConfiguration()
                    .MinimumLevel.Information()
                    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                    .MinimumLevel.Override("System", LogEventLevel.Warning)
                    .WriteTo.Console()
                    .WriteTo.Seq(builder.Configuration["Serilog:WriteTo:1:Args:serverUrl"])
                    .CreateLogger();
    builder.Host.UseSerilog(Log.Logger);
    builder
        .AppConfiguration()
        .UseApplication()
        .Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, $"{APP_NAME} service failed to start.");
}
finally
{
    Log.CloseAndFlush();
}