// <auto-generated/>
global using Omicron.Invoice.Model.Entities;
global using Omicron.Invoice.Persistence.Context;
global using Omicron.Invoice.Persistence.DAO.Invoice;
global using Omicron.Invoice.Persistence.DAO.Invoice.Impl;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;