import {
  MatToolbarModule,
  MatInputModule,
  MatButtonModule,
  MatProgressBarModule,
  MatCardModule,
  MatSidenavModule,
  MatListModule,
  MatSnackBarModule,
  MatIconModule,
  MatMenuModule,
  MatSelectModule,
  MatExpansionModule,
  MatPaginatorModule,
  MatTableModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatTabsModule,
  MatProgressSpinnerModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatAutocompleteModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatTooltipModule,
  MatBadgeModule

} from '@angular/material';


export const MATERIAL_COMPONENTS = [
  MatBadgeModule,
  MatToolbarModule,
  MatInputModule,
  MatButtonModule,
  MatProgressBarModule,
  MatCardModule,
  MatSidenavModule,
  MatListModule,
  MatSnackBarModule,
  MatIconModule,
  MatMenuModule,
  MatSelectModule,
  MatExpansionModule,
  MatPaginatorModule,
  MatTableModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatTabsModule,
  MatProgressSpinnerModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatRadioModule,
  MatAutocompleteModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatTooltipModule
];
