name: sonar-net

inputs:
  path:
    required: true
    type: string
  project_name:
    required: true
    type: string
  environment:
    required: true
    type: string
  sonar_server:
    required: true
    type: string
  sonar_token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: set sonar token env
      run: echo "SONAR_TOKEN=${{ inputs.sonar_token }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: sonar-scanner
      uses: highbyte/sonarscan-dotnet@v2.2.1
      with:
        sonarProjectKey: ${{ inputs.project_name }}
        sonarProjectName: ${{ inputs.project_name }}
        sonarHostname: ${{ inputs.sonar_server }}
