name: sonar-net

inputs:
  path:
    required: true
    type: string
  project_name:
    required: true
    type: string
  environment:
    required: true
    type: string
  sonar_server:
    required: true
    type: string
  sonar_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: sonar-scanner
      run: |
        dotnet /opt/sonar-scanner-ms/SonarScanner.MSBuild.dll begin /k:'20_Omicron_AppiOSFormulas_${{ inputs.project_name }}_${{ inputs.environment }}' /d:sonar.host.url='${{ inputs.sonar_server }}' /d:sonar.login='${{ inputs.sonar_token }}' /d:sonar.cs.opencover.reportsPaths='Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test/TestResults/coverage.opencover.xml' /d:sonar.coverage.exclusions='**Test*.cs, **/Controllers/**/*, **DependencyInjector.cs, **Startup.cs, **Program.cs, Omicron.${{ inputs.project_name }}.Api/**'
        dotnet build Omicron.${{ inputs.project_name }}.Microservice.sln
        dotnet test Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"TestResults/\"
        dotnet build-server shutdown
        dotnet /opt/sonar-scanner-ms/SonarScanner.MSBuild.dll end /d:sonar.login='${{ inputs.sonar_token }}'
      working-directory: ${{ inputs.path }}
      shell: bash
