name: sonar-net

inputs:
  path:
    required: true
    type: string
  project_name:
    required: true
    type: string
  sonar_server:
    required: true
    type: string
  sonar_token:
    required: true
    type: string
  nexus_user:
    required: false
    type: string
  nexus_pass:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: sonar-scanner
      run: |
        cp nuget.config.template nuget.config
        sed -i -e "s/USER/${{ inputs.nexus_user }}/g" -e "s/PW/${{ inputs.nexus_pass }}/g" nuget.config
        dotnet sonarscanner begin /k:'20_Omicron_AppiOSFormulas_${{ inputs.project_name }}' /d:sonar.host.url='${{ inputs.sonar_server }}' /d:sonar.login='${{ inputs.sonar_token }}' /d:sonar.cs.opencover.reportsPaths='Omicron.${{ inputs.project_name }}.Test/TestResults/coverage.opencover.xml' /d:sonar.coverage.exclusions='**Test*.cs, **/Controllers/**/*, **DatabaseContext.cs, **DependencyExtension.cs, **DependencyInjector.cs, **Startup.cs, **Program.cs, Omicron.${{ inputs.project_name }}.Api/**'
        dotnet build Omicron.${{ inputs.project_name }}.Microservice.sln
        dotnet test Omicron.${{ inputs.project_name }}.Test/Omicron.${{ inputs.project_name }}.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"TestResults/\"
        dotnet sonarscanner end /d:sonar.login='${{ inputs.sonar_token }}'
      working-directory: ${{ inputs.path }}
      shell: bash
