// <auto-generated/>
global using System.Reflection;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Omicron.SapServiceLayerAdapter.Persistence.Context;
