// <auto-generated/>
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Batches;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Delivery;
global using System.Collections.Generic;
global using System.Reflection;
global using System.Text.Json.Serialization;