name: docker-build
inputs:
  path:
    required: true
    type: string
  environment:
    required: true
    type: string
  configuration:
    required: true
    type: string
    default: ""
  href:
    required: true
    type: string
    default: "/"
  registry:
    required: true
    type: string
  dockerfile:
    required: false
    type: string
    default: Dockerfile
  axity_aws_access_key_id:
    description: 'Axity Axw Access Key Id'
    required: false
  axity_aws_secret_access_key:
    description: 'Axity Aws Secret Access Key'
    required: false
  axity_aws_region:
    description: 'Axity Aws Region'
    required: false
  axity_aws_user:
    description: 'Axity Aws User'
    required: false

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.axity_aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.axity_aws_secret_access_key }}
        aws-region: ${{ inputs.axity_aws_region }}

    - name: Get AWS Nuget Token Action
      run: |
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain axity \
          --domain-owner 992382646884 \
          --region ${{ inputs.axity_aws_region }} \
          --query authorizationToken \
          --output text)
        echo "NUGET_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV
      shell: bash

    - name: Split path
      env:
        ITEM_PATH: ${{ inputs.path }}
      id: split_path
      run: echo "item_folder=${ITEM_PATH##*/}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Split path
      env:
        ITEM_NAME: ${{ steps.split_path.outputs.item_folder }}
      id: split_name
      run: echo "item_name=${ITEM_NAME%-service}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Docker build ${{ inputs.path }}
      working-directory: ${{ inputs.path }}
      run: docker build -f ${{ inputs.dockerfile }} --build-arg NUGET_AUTH_TOKEN=$NUGET_AUTH_TOKEN --build-arg NUGET_USER_NAME=${{ inputs.axity_aws_user }} --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg CONFIGURATION=${{ inputs.configuration }} --build-arg BASE_HREF=${{ inputs.href }} -t ${{ inputs.registry }}/omicron${{ inputs.environment }}/omicron-appiosformulas-${{ steps.split_name.outputs.item_name }}-repository:latest --cache-from ${{ inputs.registry }}/omicron${{ inputs.environment }}/omicron-appiosformulas-${{ steps.split_name.outputs.item_name }}-repository:latest . --progress=plain
      shell: bash
    - name: Docker push ${{ inputs.path }}
      working-directory: ${{ inputs.path }}
      run: docker push ${{ inputs.registry }}/omicron${{ inputs.environment }}/omicron-appiosformulas-${{ steps.split_name.outputs.item_name }}-repository:latest
      shell: bash
