// <auto-generated/>
global using AutoMapper;
global using Microsoft.Extensions.DependencyInjection;
global using Newtonsoft.Json;
global using Omicron.Invoice.Common.DTOs.Requests.Users;
global using Omicron.Invoice.Common.DTOs.Responses.Common;
global using Omicron.Invoice.Common.DTOs.Responses.Users;
global using Omicron.Invoice.Model.Entities;
global using Omicron.Invoice.Persistence.DAO.Invoice;
global using Omicron.Invoice.Services.Invoice;
global using Omicron.Invoice.Services.Invoice.Impl;
global using Omicron.Invoice.Services.Mapping;
global using Omicron.Invoice.Services.Redis;
global using Omicron.Invoice.Services.Redis.Impl;
global using Omicron.Invoice.Services.Utils;
global using Serilog;
global using StackExchange.Redis;
global using System.Net;