// <auto-generated/>
global using AutoMapper;
global using Axity.Commons.Exceptions;
global using Axity.Commons.Extensions;
global using Omicron.Invoice.Common;
global using Omicron.Invoice.Common.DTOs.Requests.Users;
global using Omicron.Invoice.Common.DTOs.Responses.Users;
global using Omicron.Invoice.Model.Entities;
global using Omicron.Invoice.Persistence.DAO.Users;
global using Omicron.Invoice.Services.Mapping;
global using Omicron.Invoice.Services.Users;
global using Omicron.Invoice.Services.Users.Impl;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;