// <auto-generated/>
global using Microsoft.Extensions.DependencyInjection;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Requests.Users;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Responses.Common;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Responses.Users;
global using Omicron.SapServiceLayerAdapter.Facade.Orders;
global using Omicron.SapServiceLayerAdapter.Facade.Orders.Impl;
global using Omicron.SapServiceLayerAdapter.Facade.Users;
global using Omicron.SapServiceLayerAdapter.Facade.Users.Impl;
global using Omicron.SapServiceLayerAdapter.Services.Orders;
global using Omicron.SapServiceLayerAdapter.Services.Users;
global using Omicron.SapServiceLayerAdapter.Services.Utils;
global using AutoMapper;