// <auto-generated/>
global using AutoMapper;
global using Microsoft.Extensions.DependencyInjection;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Invoices;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Orders;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Responses.Common;
global using Omicron.SapServiceLayerAdapter.Facade.Invoice;
global using Omicron.SapServiceLayerAdapter.Facade.Invoice.Impl;
global using Omicron.SapServiceLayerAdapter.Facade.Orders;
global using Omicron.SapServiceLayerAdapter.Facade.Orders.Impl;
global using Omicron.SapServiceLayerAdapter.Services.Invoices;
global using Omicron.SapServiceLayerAdapter.Services.Orders;
global using Omicron.SapServiceLayerAdapter.Services.Utils;
