// <auto-generated/>
global using AutoMapper;
global using Microsoft.Extensions.DependencyInjection;
global using Omicron.SapServiceLayerAdapter.Common.DTOs.Responses.Common;
global using Omicron.SapServiceLayerAdapter.Facade.Orders;
global using Omicron.SapServiceLayerAdapter.Facade.Orders.Impl;
global using Omicron.SapServiceLayerAdapter.Facade.Orders.Impl;
global using Omicron.SapServiceLayerAdapter.Services.Orders;
global using Omicron.SapServiceLayerAdapter.Services.Utils;
