/**
 * Represents an individual SAP order record linked to an invoice.
 */
export interface SapOrderModel {
  /** Unique identifier of the SAP order record (internal DB id). */
  id: number;

  /** SAP order ID (unique identifier generated in SAP). */
  idpedidosap: string;

  /** Associated invoice ID linking this SAP order to the billing document. */
  idinvoice: string;
}

/**
 * Represents a remission (delivery note) record linked to an invoice.
 */
export interface RemissionModel {
  /** Unique identifier of the remission record (internal DB id). */
  id: number;

  /** Remission ID (unique identifier assigned to the delivery document). */
  idremission: string;

  /** Associated invoice ID linking this remission to the billing document. */
  idinvoice: string;
}

/**
 * Represents an automatic billing transaction generated by the system.
 * This model consolidates invoice details, related SAP orders, and remissions.
 */
export interface AutoBillingModel {
  /** Unique identifier of the auto-billing request. */
  requestId: string;

  /** Unique identifier of the generated SAP invoice. */
  sapInvoiceId: string;

  /** Date when the SAP invoice was created (format: YYYY-MM-DDTHH:mm:ss). */
  sapCreationDate: string;

  /** Type of invoice generated (e.g., 'A', 'B', 'Credit Note'). */
  invoiceType: string;

  /** Billing mode used (e.g., 'Automatic', 'Manual', 'Scheduled'). */
  billingMode: string;

  /** User who initiated or triggered the billing process. */
  originUser: string;

  /** Associated shop order identifier. */
  shopOrder: string;

  /** Transaction ID corresponding to the shop or POS operation. */
  shopTransaction: string;

  /** Number of SAP orders linked to this invoice. */
  sapOrder: number;

  /** Number of shipments or remissions related to this invoice. */
  shipments: number;

  /** Number of retry attempts made to process the invoice. */
  retries: number;

  /** List of SAP orders linked to this auto-billing transaction. */
  sapOrders: SapOrderModel[];

  /** List of remissions (delivery notes) associated with the invoice. */
  remissions: RemissionModel[];
}
