// <auto-generated/>
var builder = Host.CreateDefaultBuilder(args);
builder.AddPlaceholderResolver();
builder.UseSerilog((context, services, configuration) =>
{
    var settings = context.Configuration.GetSection("Settings").Get<Settings>();

    configuration.WriteTo.Console(LogEventLevel.Information);

    // Validar variables de entorno antes de construir la URL
    var seqHost = Environment.GetEnvironmentVariable("SEQLOG_SVC_SERVICE_HOST");
    var seqPort = Environment.GetEnvironmentVariable("SEQLOG_SVC_SERVICE_PORT_ALT");

    Console.WriteLine($"SEQLOG_SVC_SERVICE_HOST: '{seqHost}'");
    Console.WriteLine($"SEQLOG_SVC_SERVICE_PORT_ALT: '{seqPort}'");
    Console.WriteLine($"SeqUrl configurada: '{settings.SeqUrl}'");

    if (string.IsNullOrEmpty(seqHost) || string.IsNullOrEmpty(seqPort))
    {
        Console.WriteLine("Variables de entorno de Seq no están definidas. Omitiendo configuración de Seq.");
    }
    else if (Uri.IsWellFormedUriString(settings.SeqUrl, UriKind.Absolute))
    {
        configuration.WriteTo.Seq(settings.SeqUrl);
        Console.WriteLine("Seq configurado correctamente.");
    }
    else
    {
        Console.WriteLine($"SeqUrl malformada: '{settings.SeqUrl}'");
    }

    if (context.HostingEnvironment.IsProduction())
    {
        configuration.MinimumLevel.Override("Microsoft", LogEventLevel.Warning);
        configuration.MinimumLevel.Override("System", LogEventLevel.Warning);
    }
});

builder.ConfigureServices((hostContext, services) =>
{
    IConfiguration configuration = hostContext.Configuration;
    IHostEnvironment environment = hostContext.HostingEnvironment;

    // Configuración
    services.Configure<Settings>(configuration.GetSection(nameof(Settings)));

    // Redis
    services.AddSingleton<IConnectionMultiplexer>(sp =>
    {
        var settings = sp.GetRequiredService<IOptions<Settings>>().Value;
        Console.WriteLine($"Redis URL: {settings.RedisUrl}");
        return ConnectionMultiplexer.Connect(settings.RedisUrl);
    });

    // HttpClient
    services.AddHttpClient<IPedidosService, PedidosService>((serviceProvider, client) =>
    {
        var settings = serviceProvider.GetRequiredService<IOptions<Settings>>().Value;
        Console.WriteLine($"Pedidos URL: {settings.PedidosUrl}");
        client.BaseAddress = new Uri(settings.PedidosUrl);
        client.Timeout = TimeSpan.FromMinutes(3);
    });

    // Otros servicios
    services.AddTransient<IFinalizeProductionOrderHandler, FinalizeProductionOrderHandler>();
    services.AddTransient<IRedisService, RedisService>();
});

var host = builder.Build();
using var scope = host.Services.CreateScope();
var handler = scope.ServiceProvider.GetRequiredService<IFinalizeProductionOrderHandler>();
await handler.Handle();